### ISSUE TITLE
Missing controlled airspaces ?

### ISSUE THREAD

**Issue by jgaida** [SpotAiR/SpotAiR#16]
It seems that the NANCY1.2 TMA is missing on the map. I don't understand why because this control area is available in both Openaip and Pascal Bazile OpenAir Files which are the sources of SportAiR for controlled airspaces.

See : https://www.openaip.net/data/airspaces/64428ed90fa6f452525e9929

**Comment by SpotAiR** [comment]
Hi,
It's not missing. Just not displayed because of the default airspaces settings.
Default settings are : airspaces entirely above 1500m are not displayed. Nancy TMA 1.2 has a floor at 5000ft which is around 1520m and so is above 1500m).
If you change this setting, for example by specifying 2000m (or 6000ft) as top limit, the Nancy TMA 1.2 is then displayed.

**Comment by jgaida** [comment]
Sorry for this false report. I was unaware of this setting option. Everything works perfectly. Thank you for your quick reply !
