### ISSUE TITLE
Some webcams disappeared

### ISSUE THREAD

**Issue by guillaumedc** [SpotAiR/SpotAiR#6]
Some webcams disappear from the map.
It's not possible to add them back (still present in webcams tool).

Concerned webcam: https://www.skaping.com/la-feclaz/stade-de-biathlon

**Comment by SpotAiR** [comment]
Yes, problem with all Skaping webcams.

Why ? For example with Feclaz - Stade de biathlon
- periodicity of 30 minutes, but sometimes it's less or more, 29 minutes, 31 minutes... so the image url is not predictable
- when a webcam image cannot be reached for days, it disappears from SpotAiR,  That's an automatic process to remove automatically the frozen webcams.

Skaping as been contacted, they are based in Grenoble like me, but they do not want to change that because they don't like that other websites like SpotAiR to make links to their webcams.
